app/post/controllers.py
from app.core.controllers import *
from app.post.forms import PostForm
from app.auth.models import User
from app.post.models import Post, Tag, Category

mod_post = Blueprint('posts', __name__, url_prefix='/posts')

@mod_post.before_request
def before_request():
    if 'user_id' not in session:
        return redirect('/auth/login/')

@mod_post.route('/new/', methods=['GET', 'POST'])
def new():
    method = 'POST'
    action = '.'
    form = PostForm(request.form)
    if form.validate_on_submit():
        post = Post()
        post = set_post(post,form)
        print(post)
        post.put()
        flash('Post created!')
        return redirect(url_for('.index'))
    return render_template("posts/new.html", form=form, method=method, action=action)

@mod_post.route('/')
def index():
    posts = Post.query().order(-Post.created_at)
    return render_template("posts/index.html", posts=posts)

@mod_post.route('/<int:id>/edit/', methods=['GET', 'POST'])
def edit(id):
    method = 'POST'
    action = '.'
    post = Post.get_by_id(id)
    form = PostForm(request.form, post)
    form.category.data = post.category.name
    tags = []
    for tag in post.tags:
        tags.append(tag.name)
    form.tags.data = ','.join(tags)
    if form.validate_on_submit():
        post = set_post(post,form)
        post.put()
        flash('Post updated!')
    return render_template("posts/edit.html", form=form, method=method, action=action)


def set_post(post,form):
    post.title=form.title.data
    if(post.url==None or post.url==''):
        post.url=post.slugify(post.title)
    else:
        post.url=post.slugify(post.url)
    post.description=form.description.data
    post.content=form.content.data
    post.post_type=form.post_type.data
    post.post_status=form.post_status.data
    post.author=User.get_by_id(session['user_id'])
    post.category=Category(name=form.category.data)
    my_tags = []
    for tag in form.tags.data.lower().split(','):
        my_tags.append(Tag(name=tag))
    post.tags=my_tags

    return post

app/worship/controllers.py
from app.core.controllers import *
from app.worship.forms import WorshipForm
from app.worship.models import Worship

mod_worship = Blueprint('worships', __name__, url_prefix='/worships')

@mod_worship.before_request
def before_request():
    if 'user_id' not in session:
        return redirect('/auth/login/')

@mod_worship.route('/')
def index():
    worships = Worship.query()
    return render_template("worships/index.html",worships=worships)

@mod_worship.route('/new/', methods=['GET', 'POST'])
def new():
    method = 'POST'
    action = '.'
    form = WorshipForm(request.form)
    if form.validate_on_submit():
        worship = Worship()
        form.populate_obj(worship)
        worship.put()
        flash('Worship created!')
        return redirect(url_for('.index'))
    return render_template("worships/new.html", form=form, method=method, action=action)

@mod_worship.route('/<int:id>/edit/',methods=['GET','POST'])
def edit(id):
    method = 'POST'
    action = '.'
    worship = Worship.get_by_id(id)
    form = WorshipForm(request.form, worship)
    if form.validate_on_submit():
        worship = Worship.get_by_id(id)
        form.populate_obj(worship)
        worship.put()
        flash('Worship updated!')
    return render_template("worships/edit.html", form=form, method=method, action=action)

app/templates/admin_layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Lírio CMS Admin</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/style.css') }}">
  </head>
  <body>
     <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Lírio CMS</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle {% if request.url_rule.rule.find('post')!=-1 %}dropdown-active{% endif %}" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Posts <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{url_for('posts.index')}}">All Posts</a></li>
                <li><a href="{{url_for('posts.new')}}">New Post</a></li>
              </ul>
            </li>
            <li>
              <a href="#" class="dropdown-toggle {% if request.url_rule.rule.find('worship')!=-1 %}dropdown-active{% endif %}" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Worships <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{url_for('worships.index')}}">All Worships</a></li>
                <li><a href="{{url_for('worships.new')}}">New Worship</a></li>
              </ul>
            </li>
          </ul>
          <p class="navbar-text navbar-right">
            {% if logged_user and google_users.is_current_user_admin() %}
                <a class="navbar-link" href="{{google_users.create_logout_url('/')}}">Sair</a>
            {% elif session['user_id'] %}
                <a class="navbar-link" href="/auth/logout/">Sair</a>
            {% else %}
                <a class="navbar-link" href="/auth/login/">Login</a>
            {% endif %}
          </p>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% for message in get_flashed_messages() %}
      <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
    <div class="container">
    {% block body %}{% endblock %}
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </body>
</html>

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Lírio CMS</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/style.css') }}">
    {% block custom_css %}
    {% endblock %}
    {% block tag_description %}
    {% endblock %}
    {% block tag_keywords %}
    {% endblock %}
  </head>
  <body>
     <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Lírio CMS</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/about">About</a></li>
            <li><a href="/contacts">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% for message in get_flashed_messages() %}
      <div class=flash>{{ message }}</div>
    {% endfor %}
    <div class="container">
    {% block body %}{% endblock %}
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>